-- Supabase schema for VitaData demo

-- Contacts table (public inserts allowed when row level security and policies configured)
CREATE TABLE IF NOT EXISTS public.contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  message text,
  created_at timestamptz DEFAULT now()
);

-- Appointments table (demo appointments from chatbot quick-picks)
CREATE TABLE IF NOT EXISTS public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  when text,
  meta text,
  created_at timestamptz DEFAULT now()
);

-- IMPORTANT: for client-side anon key usage, enable Row Level Security and add policies that allow
-- authenticated or anonymous inserts as appropriate. Example policy (allow insert for anon):
-- ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow anon insert contacts" ON public.contacts FOR INSERT USING (true) WITH CHECK (true);
